import { createElement } from "react";
import {
  Award,
  BookOpen,
  BookOpenCheck,
  Bot,
  BriefcaseBusiness,
  ChartLine,
  CircleCheck,
  ClipboardCheck,
  Clock,
  Cpu,
  FileText,
  Gift,
  GraduationCap,
  Headphones,
  Heart,
  Lightbulb,
  Megaphone,
  MessageSquareText,
  MonitorPlay,
  PenLine,
  Play,
  Rocket,
  Search,
  Settings,
  ShieldCheck,
  Sparkles,
  Star,
  Target,
  UserRound,
  Users,
  Video,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const ICONS: Record<string, { icon: LucideIcon; label: string }> = {
  megaphone: { icon: Megaphone, label: "Loa" },
  pen: { icon: PenLine, label: "Bút" },
  search: { icon: Search, label: "Tìm kiếm" },
  video: { icon: Video, label: "Video" },
  play: { icon: Play, label: "Phát" },
  monitor: { icon: MonitorPlay, label: "Màn hình" },
  user: { icon: UserRound, label: "Người" },
  users: { icon: Users, label: "Nhóm" },
  bot: { icon: Bot, label: "Robot" },
  chip: { icon: Cpu, label: "Chip" },
  gear: { icon: Settings, label: "Bánh răng" },
  target: { icon: Target, label: "Mục tiêu" },
  headphones: { icon: Headphones, label: "Hỗ trợ" },
  message: { icon: MessageSquareText, label: "Tin nhắn" },
  check: { icon: ClipboardCheck, label: "Checklist" },
  circleCheck: { icon: CircleCheck, label: "Dấu tích" },
  file: { icon: FileText, label: "Tài liệu" },
  book: { icon: BookOpen, label: "Sách" },
  bookCheck: { icon: BookOpenCheck, label: "Bài học" },
  gift: { icon: Gift, label: "Quà" },
  cap: { icon: GraduationCap, label: "Tốt nghiệp" },
  award: { icon: Award, label: "Giải thưởng" },
  star: { icon: Star, label: "Ngôi sao" },
  heart: { icon: Heart, label: "Trái tim" },
  rocket: { icon: Rocket, label: "Tên lửa" },
  zap: { icon: Zap, label: "Tia chớp" },
  sparkles: { icon: Sparkles, label: "Lấp lánh" },
  idea: { icon: Lightbulb, label: "Ý tưởng" },
  chart: { icon: ChartLine, label: "Biểu đồ" },
  briefcase: { icon: BriefcaseBusiness, label: "Công việc" },
  clock: { icon: Clock, label: "Đồng hồ" },
  shield: { icon: ShieldCheck, label: "Bảo vệ" },
};

export const iconOf = (name: string): LucideIcon => (ICONS[name] ?? ICONS.sparkles).icon;

/** Vẽ biểu tượng theo tên đã lưu trong nội dung. */
export function IconView({ name, className }: { name: string; className?: string }) {
  return createElement(iconOf(name), { className, "aria-hidden": true });
}
